language: c
compiler:
        - gcc
before_script:
        - sudo apt-get update && sudo apt-get install -y git wget bison flex libgmp-dev libreadline-dev libssl-dev linux-libc-dev=3.13.0-46.79
        - (wget -O - ftp://ftp.netfilter.org/pub/libmnl/libmnl-1.0.3.tar.bz2 | tar xvfpj -; cd libmnl-1.0.3; ./configure; make ; sudo make install)
        - (wget -O - ftp://ftp.netfilter.org/pub/libnftnl/libnftnl-1.0.3.tar.bz2 | tar xvfpj - ; cd libnftnl-1.0.3; ./configure; make ; sudo make install)
        - (wget -O - ftp://ftp.netfilter.org/pub/nftables/nftables-0.4.tar.bz2 | tar xvfpj - ; cd nftables-0.4; ./configure; make; sudo make install)
        - (wget -O - ftp://ftp.netfilter.org/pub/libnfnetlink/libnfnetlink-1.0.1.tar.bz2 | tar xvfpj -; cd libnfnetlink-1.0.1; ./configure; make ; sudo make install)
script:
        - cd miniupnpd && make -f Makefile.linux_nft config.h all
