language: c
compiler:
  - gcc
  - clang

git:
  depth: 1

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - iptables-dev
    - libevent-dev
    - libnfnetlink-dev

sudo: false

env:
  - 'PROJECT=minissdpd'
  - 'PROJECT=miniupnpc'
  - 'PROJECT=miniupnpc-async'
  - 'PROJECT=miniupnpc-libevent'
  - 'PROJECT=miniupnpd'

script:
  - 'cd $TRAVIS_BUILD_DIR && cd $PROJECT'
  - 'MAKEFILE=Makefile && if [ -a Makefile.linux ]; then MAKEFILE=Makefile.linux; fi'
  - 'make -f $MAKEFILE -j2'
  - 'if [ "$PROJECT" = "miniupnpc" ]; then make -f $MAKEFILE check; fi'
