language: c

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - iptables-dev
    - libevent-dev
    - libnfnetlink-dev

# container-based builds
sudo: false

env:
  - 'PROJECT=minissdpd'
  - 'PROJECT=miniupnpc'
  - 'PROJECT=miniupnpc-async'
  - 'PROJECT=miniupnpc-libevent'
  - 'PROJECT=miniupnpd'

compiler:
  - gcc
  - clang

script:
  - 'cd $TRAVIS_BUILD_DIR && cd $PROJECT'
  - 'MAKEFILE=Makefile && if [ -a Makefile.linux ]; then MAKEFILE=Makefile.linux; fi'
  - 'make -f $MAKEFILE -j3 && if [ "$PROJECT" = "miniupnpc" -o "$PROJECT" = "minissdpd" ]; then make -f $MAKEFILE check; fi && if [ "$PROJECT" = "miniupnpc" ]; then make -f $MAKEFILE pythonmodule; fi'

after_success:
  - 'INSTALLPREFIX="$HOME/$PROJECT" make -f $MAKEFILE install'
