install:
  - set PATH=%PATH%;C:\msys64\mingw32\bin

build_script:
  - cd miniupnpc
  - mingw32-make -f Makefile.mingw
  - mingw32-make -f Makefile.mingw pythonmodule PYTHON=C:\Python27\python
#  - upnpc-static.exe -l
