environment:
  APP_VERSION: '2.1'


version: '$(APP_VERSION).{build}'

image: Visual Studio 2017

install:
  - set PATH=%PATH%;C:\msys64\mingw32\bin

build_script:
  - cd miniupnpc
  - appveyor AddCompilationMessage "Building miniupnpc"
  - mingw32-make -f Makefile.mingw
  - mingw32-make -f Makefile.mingw pythonmodule PYTHON=C:\Python37\python

after_build:
  - 7z a ..\miniupnpc-%APPVEYOR_BUILD_VERSION%.zip *.exe *.dll *.a *.lib

artifacts:
  - path: miniupnpc-$(appveyor_build_version).zip
    name: miniupnpc binaries
  - path: miniupnpc/dist/miniupnpc-$(APP_VERSION)-py3.7-win32.egg
    name: miniupnpc python module
